[package]
name = "urlbum"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.7"
rusqlite = { version = "0.32", features = ["bundled"] }
webbrowser = "1.2"
ureq  = { version = "2", default-features = false, features = ["tls"] }
arboard = "3"
rfd = "0.15"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp", "ico"] }

[build-dependencies]
slint-build = "1.7"
